import { CheatEnum } from "./CheatType";
export const enum CMD {
  F1 = 'f1',
  F2 = 'f2',
  F3 = 'f3',
  F4 = 'f4',
  F5 = 'f5',
  F6 = 'f6',
  F7 = 'f7',
  F8 = 'f8',
  F9 = 'f9',
  F10 = 'f10',
  LF2_NET = CheatEnum.LF2_NET,
  HERO_FT = CheatEnum.HERO_FT,
  GIM_INK = CheatEnum.GIM_INK,
  KILL_ENEMIES = 'KILL_ENEMIES',
  KILL_BOSS = 'KILL_BOSS',
  KILL_SOLIDERS = 'KILL_SOLIDERS',
  KILL_OTHERS = 'KILL_OTHERS',
  DEL_PUPPET = 'DEL_PUPPET',
  SET_DIFFICULTY = "SET_DIFFICULTY",
  DIST_CAM = "DIST_CAM",
  LOCK_CAM = "LOCK_CAM",
  CHANGE_BG = "CHANGE_BG",
  CHANGE_STAGE = "CHANGE_STAGE",
  PAUSE = "PAUSE",
}
export const CMD_NAMES: Record<CMD, string> = {
  [CMD.F1]: "F1",
  [CMD.F2]: "F2",
  [CMD.F3]: "F3",
  [CMD.F4]: "F4",
  [CMD.F5]: "F5",
  [CMD.F6]: "F6",
  [CMD.F7]: "F7",
  [CMD.F8]: "F8",
  [CMD.F9]: "F9",
  [CMD.F10]: "F10",
  [CMD.LF2_NET]: "LF2_NET",
  [CMD.HERO_FT]: "HERO_FT",
  [CMD.GIM_INK]: "GIM_INK",
  [CMD.KILL_ENEMIES]: "KILL_ENEMIES",
  [CMD.KILL_BOSS]: "KILL_BOSS",
  [CMD.KILL_SOLIDERS]: "KILL_SOLIDERS",
  [CMD.KILL_OTHERS]: "KILL_OTHERS",
  [CMD.DEL_PUPPET]: "DEL_PUPPET",
  [CMD.SET_DIFFICULTY]: "SET_DIFFICULTY",
  [CMD.DIST_CAM]: "DIST_CAM",
  [CMD.LOCK_CAM]: "LOCK_CAM",
  [CMD.CHANGE_BG]: "CHANGE_BG",
  [CMD.CHANGE_STAGE]: "CHANGE_STAGE",
  [CMD.PAUSE]: "PAUSE"
}