import { CheatType } from "./CheatType";
export enum CMD {
  F1 = 'f1',
  F2 = 'f2',
  F4 = 'f4',
  F5 = 'f5',
  F6 = 'f6',
  F7 = 'f7',
  F8 = 'f8',
  F9 = 'f9',
  F10 = 'f10',
  LF2_NET = CheatType.LF2_NET,
  HERO_FT = CheatType.HERO_FT,
  GIM_INK = CheatType.GIM_INK,
  LF2_NET_ON = CheatType.LF2_NET + '#',
  HERO_FT_ON = CheatType.HERO_FT + '#',
  GIM_INK_ON = CheatType.GIM_INK + '#',
  LF2_NET_OFF = CheatType.LF2_NET + '#1',
  HERO_FT_OFF = CheatType.HERO_FT + '#1',
  GIM_INK_OFF = CheatType.GIM_INK + '#1',
  KILL_ENEMIES = 'KILL_ENEMIES',
  KILL_BOSS = 'KILL_BOSS',
  KILL_SOLIDERS = 'KILL_SOLIDERS',
  KILL_OTHERS = 'KILL_OTHERS',
  DEL_PUPPET = 'DEL_PUPPET',
  SET_DIFFICULTY = "SET_DIFFICULTY",
}
export const CMD_NAMES: Record<CMD, string> = {
  [CMD.F1]: "F1",
  [CMD.F2]: "F2",
  [CMD.F4]: "F4",
  [CMD.F5]: "F5",
  [CMD.F6]: "F6",
  [CMD.F7]: "F7",
  [CMD.F8]: "F8",
  [CMD.F9]: "F9",
  [CMD.F10]: "F10",
  [CMD.LF2_NET]: "LF2_NET",
  [CMD.HERO_FT]: "HERO_FT",
  [CMD.GIM_INK]: "GIM_INK",
  [CMD.KILL_ENEMIES]: "KILL_ENEMIES",
  [CMD.KILL_BOSS]: "KILL_BOSS",
  [CMD.KILL_SOLIDERS]: "KILL_SOLIDERS",
  [CMD.KILL_OTHERS]: "KILL_OTHERS",
  [CMD.DEL_PUPPET]: "DEL_PUPPET",
  [CMD.SET_DIFFICULTY]: "SET_DIFFICULTY",
  [CMD.LF2_NET_ON]: "LF2_NET#",
  [CMD.HERO_FT_ON]: "HERO_FT#",
  [CMD.GIM_INK_ON]: "GIM_INK#",
  [CMD.LF2_NET_OFF]: "LF2_NET#1",
  [CMD.HERO_FT_OFF]: "HERO_FT#1",
  [CMD.GIM_INK_OFF]: "GIM_INK#1"
}